-- Active: 1720682128560@@127.0.0.1@5432@mbaccount
DELETE * FROM unit;
DELETE * FROM function;

SELECT * FROM unit;

SELECT * FROM function;

CREATE SEQUENCE sq_unit
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;

ALTER TABLE unit ALTER COLUMN id SET DEFAULT nextval('sq_unit');
